config:
  use_colors: False

kobo:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: not used
      schema: 'main'
      schemas_and_paths:
        main: './data/KoboReader.sqlite'
      schema_directory: not used
